### ISSUE TITLE
Not started properly

### ISSUE THREAD

**Issue by jackalcooper** [MonolithProjects/ansible-github_actions_runner#102]
After installation, the services are still inactive. I has to manually run `sudo ./svc.sh start`. Is this expected?
Many thanks.

**Comment by MonolithProjects** [comment]
Hi there... The initial service state depends on `runner_state` variable. The [default](https://github.com/MonolithProjects/ansible-github_actions_runner/blob/master/defaults/main.yml#L14) state is `started`.

**Comment by jackalcooper** [comment]
> Hi there... The initial service state depends on `runner_state` variable. The [default](https://github.com/MonolithProjects/ansible-github_actions_runner/blob/master/defaults/main.yml#L14) state is `started`. 

Yes. I had set it to `started`.

**Comment by MonolithProjects** [comment]
Hmm interesting as i am unable to  reproduce this behavior.  What is your operating system and which runner version are you using?

**Comment by jackalcooper** [comment]
Ubuntu 20.04. No specified runner version(default should be newest right?)

**Comment by MonolithProjects** [comment]
Please double check your `runner_state` as on all my test environments it works just fine.

My test plabook:
```
---
- name: Install Repo runner
  user: ci-bot
  hosts: test1
  gather_facts: yes
  become: yes
  vars:
    - runner_user: runner
    - github_repo: ansible-github_actions_runner-testrepo
    - github_account: monolithprojects-testorg
    - runner_version: "latest"
    - runner_state: "started"
    - runner_labels: 
        - label1
        - repo-runner
  roles:
    - robertdebock.epel
    - ansible-github_actions_runner
   ```

Ansible output (last two tasks):
```
...
TASK [ansible-github_actions_runner : START and enable Github Actions Runner service] ************************************************************
changed: [test01]

TASK [ansible-github_actions_runner : STOP and disable Github Actions Runner service] ************************************************************
skipping: [test01]
...
```

Result:
```
ci-bot@test01:~$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

ci-bot@test01:~$ systemctl status actions.runner.monolithprojects-testorg-ansible-github_actio.test01.service
● actions.runner.monolithprojects-testorg-ansible-github_actio.test01.service - GitHub Actions Runner (monolithprojects-testorg-ansible-github_actions_runner-testrepo.test01)
     Loaded: loaded (/etc/systemd/system/actions.runner.monolithprojects-testorg-ansible-github_actio.test01.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2021-09-05 14:04:09 CEST; 31s ago
   Main PID: 7762 (runsvc.sh)
      Tasks: 22 (limit: 1740)
     Memory: 33.4M
     CGroup: /system.slice/actions.runner.monolithprojects-testorg-ansible-github_actio.test01.service
             ├─7762 /bin/bash /opt/actions-runner/runsvc.sh
             ├─7764 ./externals/node12/bin/node ./bin/RunnerService.js
             └─7782 /opt/actions-runner/bin/Runner.Listener run --startuptype service

```

**Comment by jackalcooper** [comment]
after running my playbook with `-vvvv`，there is the error：
```
fatal: [oneflow-23]: FAILED! => {
    "changed": true,
    "cmd": [
        "./svc.sh",
        "install",
        "ci-user"
    ],
    "delta": "0:00:00.012373",
    "end": "2021-09-06 10:54:43.662235",
    "invocation": {
        "module_args": {
            "_raw_params": "./svc.sh install ci-user",
            "_uses_shell": false,
            "argv": null,
            "chdir": "/home/ci-user/runners/provision",
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2021-09-06 10:54:43.649862",
    "stderr": "Failed: error: exists /etc/systemd/system/actions.runner.Oneflow-Inc.oneflow-23-provision.service",
    "stderr_lines": [
        "Failed: error: exists /etc/systemd/system/actions.runner.Oneflow-Inc.oneflow-23-provision.service"
    ],
    "stdout": "Creating launch runner in /etc/systemd/system/actions.runner.Oneflow-Inc.oneflow-23-provision.service",
    "stdout_lines": [
        "Creating launch runner in /etc/systemd/system/actions.runner.Oneflow-Inc.oneflow-23-provision.service"
    ]
}
```

**Comment by jackalcooper** [comment]
playbook
```yaml
- name: Install GitHub Actions Runner
  hosts: dev_2x
  become: yes
  gather_facts: yes
  user: caishenghang
  vars:
    - runner_user: ci-user
    - runner_state: "started"
    - runner_name: "{{ ansible_hostname }}-{{ key_label }}"
    - github_account: jackalcooper
    - runner_version: "latest"
    - github_owner: "Oneflow-Inc"
    - runner_org: yes
    - access_token: "{{ lookup('env', 'RUNNER_DEPLOY_ACCESS_TOKEN') }}"
    - runner_labels:
        - provision
    - custom_env: |
        HTTP_PROXY={{ proxy_env.HTTP_PROXY }}
        http_proxy={{ proxy_env.http_proxy }}
        HTTPS_PROXY={{ proxy_env.HTTPS_PROXY }}
        https_proxy={{ proxy_env.https_proxy }}
    - runner_dir: "/home/{{ runner_user }}/runners/{{ key_label }}"
    - hide_sensitive_logs: no
    - service_name: actions.runner._services.{{ key_label }}.service
```
