### ISSUE TITLE
How to run multiple instances of runners on same server?

### ISSUE THREAD

**Issue by zulhfreelancer** [MonolithProjects/ansible-github_actions_runner#139]
I have this in my playbook:

```yaml
---
- name: GitHub self-hosted runner
  hosts: my_host
  roles:
    - github-runner-directory <-- where I create the `runner_dir` for runners below
    - name: first-repo
      role: monolithprojects.github_actions_runner
      become: true
      runner_user: ubuntu
      github_account: my-username
      github_repo: first
      runner_dir: /opt/actions-runner/first
      access_token: redacted
    - name: second-repo
      role: monolithprojects.github_actions_runner
      become: true
      runner_user: ubuntu
      github_account: my-username
      github_repo: second
      runner_dir: /opt/actions-runner/second
      access_token: redacted
```

I wanted to install 2 instances of GH Actions self-hosted runners in one same server. They are for 2 different private GH repos under my personal account. Meaning, it's 1 to 1 mapping or 1 runner per repo relationship. I know I can install/setup this for GH organization, but that's not what I want at this point.

From what I can see, the installation for `first` repo worked fine. But not for the `second` repo. It stucked at [these lines](https://github.com/MonolithProjects/ansible-github_actions_runner/blob/master/tasks/install_runner.yml#L128-L129=).

Does anyone face the same issue or it's just me? Does `github_repo` attribute accept multiple/comma-separared values e.g. `first,second`?

**Comment by zulhfreelancer** [comment]
@MonolithProjects any idea?

**Comment by MonolithProjects** [comment]
Hi @zulhfreelancer, ... hard to say. I tested your playbook (manually pre-created the runner dirs) with the latest role release, but did not face your issue.

```yaml
- name: GitHub self-hosted runner
  hosts: test
  user: ci-bot
  roles:
    - name: first-repo
      role: monolithprojects.github_actions_runner
      become: true
      runner_user: ci-bot
      github_account: monolithprojects-testorg
      github_repo: first
      runner_dir: /opt/actions-runner/first

    - name: second-repo
      role: monolithprojects.github_actions_runner
      become: true
      runner_user: ci-bot
      github_account: monolithprojects-testorg
      github_repo: second
      runner_dir: /opt/actions-runner/second
```
result:
```bash
ci-bot@test01:~$ ps -ef |grep runsvc
ci-bot      4079       1  0 21:36 ?        00:00:00 /bin/bash /opt/actions-runner/first/runsvc.sh
ci-bot      5348       1  0 21:37 ?        00:00:00 /bin/bash /opt/actions-runner/second/runsvc.sh
```

Did you get any error message?
