### ISSUE TITLE
bug: Fails to start runner with "No such file or directory", when looking for svc.sh

### ISSUE THREAD

**Issue by ollien** [MonolithProjects/ansible-github_actions_runner#175]
### Summary

I have a playbook that uses this role to deploy self-hosted runners to some of our development hosts. The playbook has not changed, but recent iterations seem to fail with the following (`hide_sensitive_logs` need to be turned off)

```
 ________________________________________________________ 
/ TASK [monolithprojects.github_actions_runner : Install \
\ service]                                               /
 -------------------------------------------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [myhost]: FAILED! => {"changed": true, "cmd": "./svc.sh install ubuntu", "msg": "[Errno 2] No such file or directory", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
 ____________ 
```

It seems that Github has changed the entrypoint for the runner from `svc.sh` to `run.sh` (and indeed, I do not see `svc.sh` in the runner directory). I have updated to 1.18.3 and the issue seems to persist

### Issue Type

Bug Report

### Ansible Version

```console
ansible [core 2.14.8]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/nick/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/nick/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.4 (main, Jun  7 2023, 00:00:00) [GCC 12.3.1 20230508 (Red Hat 12.3.1-1)] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = False
```

### Steps to Reproduce

```yaml
- name: Add Github Actions Runner
  hosts: '{{ target }}'
  become: true
  vars:
    github_account: "myOrg"
    github_owner: "myOrg"
    runner_org: yes
    runner_name: '{{ target }}'
    runner_user: ubuntu
  roles:
    # https://github.com/MonolithProjects/ansible-github_actions_runner
    # See env variables required, here
    - role: monolithprojects.github_actions_runner
```

I have removed the org I am running this under, but I suspect this would also happen on any other org.

### Expected Results

I expect the runner to start

### Actual Results

```console
________________________________________________________ 
/ TASK [monolithprojects.github_actions_runner : Install \
\ service]                                               /
 -------------------------------------------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [myhost]: FAILED! => {"changed": true, "cmd": "./svc.sh install ubuntu", "msg": "[Errno 2] No such file or directory", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
 ____________
```
