### ISSUE TITLE
bug: New labels are not added

### ISSUE THREAD

**Issue by JulianGro** [MonolithProjects/ansible-github_actions_runner#187]
### Summary

Adding an additional label to the labels list, e.g. 
```
      runner_labels:
        - linux_aarch64
        - test
```
doesn't actually add the label on GitHub when rerunning the installation task.

If this is a limitation of the GitHub Runner software, it should be noted in the README.md.

### Issue Type

Bug Report

### Ansible Version

```console
ansible [core 2.14.11]
  config file = None
  configured module search path = ['/home/juliangro/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/juliangro/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

### Steps to Reproduce

```yaml (paste below)
- hosts: githubactionsrunners
  name: GitHub Actions Runners
  gather_facts: true
  become: yes
  tasks:
    - name: "Install GitHub Actions Runner"
      ansible.builtin.import_role:
        name:
          MonolithProjects.github_actions_runner
      vars:
        access_token: github_actions_access_token
        github_account: account
        github_repo: repo
        runner_labels:
          - linux_aarch64
          - testinium
```

### Expected Results

The task should add new labels. (Removing old labels may be problematic, as one can add labels via the GitHub runner settings.)

### Actual Results

```console
The new label does not get added.
```
