### ISSUE TITLE
bug: `Replace registered runner for organization` step is missing from `install_runner.yml`

### ISSUE THREAD

**Issue by samgiz** [MonolithProjects/ansible-github_actions_runner#207]
### Summary

The `Replace registered runner for organization step` step used to exist and got removed in [this commit](https://github.com/MonolithProjects/ansible-github_actions_runner/commit/560eca78b4da055042f8429fb08c388a1a922704), even though that change isn't mentioned in the commit message.

I'm assuming that was an accidental removal. I don't see a reason to have a `Replace registered runner` step for repos but not organizations, and I don't think it's currently possible to re-register an organization runner.

### Issue Type

Bug Report

### Ansible Version

```console
1.15.0 and later.
```

### Steps to Reproduce

I'm not knowledgable enough about ansible to quickly set up a full small reproducer. I have something similar to the following snippet in my config:
```yaml (paste below)
- name: Configure the runner
  ansible.builtin.include_role:
    name: github_actions_runner
    apply:
      become: true
  vars:
    reinstall_runner: true
    runner_org: true
```

### Expected Results

I would expect the runner to be reinstalled when `reinstall_runner` is true. 

### Actual Results

It doesn't get reinstalled, because it never gets reinstalled for organization runners as currently written.

```
TASK [github_actions_runner : Set complete GitHub url for enterprise runner] **************************
skipping: [xxx]

TASK [github_actions_runner : Register runner] ********************************************************
skipping: [xxx]
```
